#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef VISXSDK_SWIFT_H
#define VISXSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVKit;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="VisxSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@interface AVPlayerViewController (SWIFT_EXTENSION(VisxSDK))
- (void)viewWillDisappear:(BOOL)animated;
@end


SWIFT_CLASS("_TtC7VisxSDK16LayoutConstraint")
@interface LayoutConstraint : NSLayoutConstraint
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

@interface LayoutConstraint (SWIFT_EXTENSION(VisxSDK))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC7VisxSDK9Mediation")
@interface Mediation : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSIndexPath;
@class VisxCollectionViewCell;

@interface UICollectionView (SWIFT_EXTENSION(VisxSDK))
- (VisxCollectionViewCell * _Nonnull)dequeueVisxCellFor:(NSIndexPath * _Nonnull)indexPath reuseIdentifier:(NSString * _Nonnull)reuseIdentifier SWIFT_WARN_UNUSED_RESULT;
@end





@class VisxTableViewCell;

@interface UITableView (SWIFT_EXTENSION(VisxSDK))
- (VisxTableViewCell * _Nonnull)dequeueVisxCellFor:(NSIndexPath * _Nonnull)indexPath reuseIdentifier:(NSString * _Nonnull)reuseIdentifier SWIFT_WARN_UNUSED_RESULT;
@end







@class UIViewController;
@class NSCoder;

SWIFT_CLASS("_TtC7VisxSDK10VisxAdView")
@interface VisxAdView : UIView <UIScrollViewDelegate>
@property (nonatomic) BOOL isMediationAdView;
@property (nonatomic, readonly, copy) NSString * _Nonnull adUnit;
@property (nonatomic) BOOL hasMessageAbove;
@property (nonatomic, strong) UIViewController * _Nullable viewControllerForPresenting;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)didMoveToSuperview;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end






@protocol VisxAdViewDelegate;
@protocol VisxHeaderBiddingDelegate;
@class UIScrollView;
@class UIColor;
@class NSError;

@interface VisxAdView (SWIFT_EXTENSION(VisxSDK))
/// VisxAdView - Default initializer using callbacks
- (nonnull instancetype)initWithAdUnit:(NSString * _Nonnull)adUnit adSize:(CGSize)adSize fixedSize:(BOOL)fixedSize viewControllerForPresenting:(UIViewController * _Nullable)viewControllerForPresenting interstitial:(BOOL)interstitial headerBidding:(BOOL)headerBidding;
/// VisxAdView - Default initializer using delegates
- (nonnull instancetype)initWithAdUnit:(NSString * _Nonnull)adUnit adViewDelegate:(id <VisxAdViewDelegate> _Nonnull)adViewDelegate adSize:(CGSize)adSize fixedSize:(BOOL)fixedSize interstitial:(BOOL)interstitial;
/// VisxAdView - Header Bidding initializer using delegates
- (nonnull instancetype)initWithAdUnit:(NSString * _Nonnull)adUnit headerBiddingDelegate:(id <VisxHeaderBiddingDelegate> _Nonnull)headerBiddingDelegate adSize:(CGSize)adSize fixedSize:(BOOL)fixedSize interstitial:(BOOL)interstitial;
/// VisxAdView - Adaptive banner initializer with dynamic size
- (nonnull instancetype)initWithAdUnit:(NSString * _Nonnull)adUnit adViewDelegate:(id <VisxAdViewDelegate> _Nonnull)adViewDelegate interstitial:(BOOL)interstitial;
/// Returns current VisxSDK version
- (NSString * _Nonnull)getSdkVersion SWIFT_WARN_UNUSED_RESULT;
/// Sets absolute position of the visible view where creative can be shown.
/// Note: Ad container is the UIView which is adding creative as a subview.
/// \param anchorX Absolute x position of ad container in which creative is added.
///
/// \param anchorY Absolute top y position of UIScrollView/UITableView.
///
/// \param anchorWidth Max width of the ad container.
///
/// \param anchorHeight Max height of the UIScrollView/UITableView.
///
- (void)setAnchorFrameWith:(double)anchorX :(double)anchorY :(double)anchorWidth :(double)anchorHeight;
/// Loads request
- (void)load;
/// Loads request with custom targeting parameters
- (void)loadWithCustomTargetingParametersWithParams:(NSDictionary<NSString *, NSString *> * _Nonnull)params;
/// Sets advertising label above the creative
- (void)advertisingLabelTextWithLabel:(NSString * _Nonnull)label;
/// Deallocates current VisxAdView
- (void)deallocAdView;
/// Returns visxAdView
- (UIView * _Nonnull)getCreativeInScrollviewWithScroll:(UIScrollView * _Nonnull)scroll SWIFT_WARN_UNUSED_RESULT;
/// Returns reactive visxAdView
- (UIView * _Nullable)getReactiveCreative SWIFT_WARN_UNUSED_RESULT;
/// Presents interstitial ad from current UIViewController
- (void)showInterstitial;
/// Presents interstitial ad from specifed UIViewController
- (void)showInterstitialFromViewControllerWithController:(UIViewController * _Nonnull)controller;
/// AdView scrollDidScroll method enables understitial effect
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
/// Check if placement type is interstitial
- (BOOL)isInterstitial SWIFT_WARN_UNUSED_RESULT;
/// Set interstitial background color, clear is default
- (void)setInterstitialBackgroundColorWithColor:(UIColor * _Nonnull)color;
/// Used only when header bidding is enabled, renderAd() needs to be called to show creative
- (void)renderAd;
/// Add a friendly obstruction for the OM SDK.
/// Note: This method should be called after VisxAdView is initialized in the ‘visxAdViewDidInitialize’ delegate or ‘onInitialize’ callback.
/// \param view The view to be marked as a friendly obstruction.
///
/// \param detailedReason A detailed reason explaining why the view is considered a friendly obstruction.
///
- (void)addFriendlyObstractionWithView:(UIView * _Nonnull)view detailedReason:(NSString * _Nonnull)detailedReason;
/// Add friendly obstructions for the OM SDK in a dictionary format [UIView: String].
/// Note: This method should be called after VisxAdView is initialized in the ‘visxAdViewDidInitialize’ delegate or ‘onInitialize’ callback.
/// <ul>
///   <li>
///     Parameter:
///     <ul>
///       <li>
///         viewsAndReasons: A dictionary containing views and their corresponding detailed reasons for being considered friendly obstructions.
///       </li>
///     </ul>
///   </li>
/// </ul>
- (void)addFriendlyObstractionWithViewsAndReasons:(NSDictionary<UIView *, NSString *> * _Nonnull)viewsAndReasons;
- (void)adViewDidReceiveAdWithBannerView:(UIView * _Nonnull)bannerView;
- (void)didFailToReceiveAdWithErrorWithBannerView:(UIView * _Nonnull)bannerView error:(NSError * _Nonnull)error;
@end



enum VisxPlacementEffect : NSInteger;

SWIFT_PROTOCOL("_TtP7VisxSDK18VisxAdViewDelegate_")
@protocol VisxAdViewDelegate
- (UIViewController * _Nonnull)viewControllerForPresentingVisxAdView SWIFT_WARN_UNUSED_RESULT;
- (void)visxAdViewDidInitializeWithVisxAdView:(VisxAdView * _Nonnull)visxAdView effect:(enum VisxPlacementEffect)effect;
@optional
- (void)visxAdFailedWithErrorWithVisxAdView:(VisxAdView * _Nonnull)visxAdView message:(NSString * _Nonnull)message code:(NSInteger)code;
- (void)visxAdViewSizeChangeWithVisxAdView:(VisxAdView * _Nonnull)visxAdView width:(CGFloat)width height:(CGFloat)height;
- (void)visxAdViewEffectChangeWithVisxAdView:(VisxAdView * _Nonnull)visxAdView effect:(enum VisxPlacementEffect)effect;
- (void)visxAdViewClosedWithVisxAdView:(VisxAdView * _Nonnull)visxAdView;
- (void)visxAdViewClickedWithVisxAdView:(VisxAdView * _Nonnull)visxAdView;
- (void)visxLandingPageOpened;
- (void)appShouldSuspendForAdWithVisxAdView:(VisxAdView * _Nonnull)visxAdView;
- (void)appShouldResumeFromAdWithVisxAdView:(VisxAdView * _Nonnull)visxAdView;
- (void)visxAdVideoFinishedWithVisxAdView:(VisxAdView * _Nonnull)visxAdView;
- (void)visxAdInterstitialWillBeClosedWithVisxAdView:(VisxAdView * _Nonnull)visxAdView;
- (void)visxAdInterstitialClosedWithVisxAdView:(VisxAdView * _Nonnull)visxAdView;
- (void)visxAdStickyOpenedWithVisxAdView:(VisxAdView * _Nonnull)visxAdView;
- (void)visxAdStickyWillBeClosedWithVisxAdView:(VisxAdView * _Nonnull)visxAdView;
- (void)visxAdStickyClosedWithVisxAdView:(VisxAdView * _Nonnull)visxAdView;
@end


SWIFT_CLASS_NAMED("VisxCollectionViewCell")
@interface VisxCollectionViewCell : UICollectionViewCell
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull visxCellIdentifier;)
+ (NSString * _Nonnull)visxCellIdentifier SWIFT_WARN_UNUSED_RESULT;
- (void)showAdWithAdView:(VisxAdView * _Nonnull)adView collectionView:(UICollectionView * _Nonnull)collectionView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP7VisxSDK25VisxHeaderBiddingDelegate_")
@protocol VisxHeaderBiddingDelegate <VisxAdViewDelegate>
@optional
- (void)visxAdRequestStartedWithVisxAdView:(VisxAdView * _Nonnull)visxAdView;
@required
- (void)visxAdResponseReceivedWithVisxAdView:(VisxAdView * _Nonnull)visxAdView price:(NSDecimal)price currency:(NSString * _Nonnull)currency;
@end


SWIFT_CLASS("_TtC7VisxSDK18VisxMediationUtils")
@interface VisxMediationUtils : NSObject
/// Returns the top most view controller
+ (UIViewController * _Nullable)topMostController SWIFT_WARN_UNUSED_RESULT;
/// Returns visxAdSize from mediation response
+ (CGSize)visxGetAdSizeFromStringWithServerParameter:(NSString * _Nonnull)serverParameter SWIFT_WARN_UNUSED_RESULT;
/// Returns NSString const for notification center
+ (NSString * _Nonnull)visxGoogleAdUpdatedViewString SWIFT_WARN_UNUSED_RESULT;
/// Returns creative Id from mediation response
+ (NSString * _Nonnull)visxGetAUIDFromStringWithServerParameter:(NSString * _Nonnull)serverParameter SWIFT_WARN_UNUSED_RESULT;
/// Returns publisher app domian from mediation response
+ (NSString * _Nonnull)visxGetAppDomainFromStringWithServerParameter:(NSString * _Nonnull)serverParameter SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, VisxPlacementEffect, open) {
  VisxPlacementEffectFullscreenOverlay = 0,
  VisxPlacementEffectSitebar = 1,
  VisxPlacementEffectSticky = 2,
  VisxPlacementEffectInlineToSticky = 3,
  VisxPlacementEffectUnderstitialMini = 4,
  VisxPlacementEffectUnderstitialMiniToSticky = 5,
  VisxPlacementEffectZoom = 6,
  VisxPlacementEffectZoomToSticky = 7,
  VisxPlacementEffectNone = 8,
};

typedef SWIFT_ENUM(NSInteger, VisxPlacementType, open) {
  VisxPlacementTypeInline = 0,
  VisxPlacementTypeInterstitial = 1,
};


SWIFT_CLASS_NAMED("VisxSDKManager")
@interface VisxSDKManager : NSObject
+ (VisxSDKManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)initializeSDK;
- (NSString * _Nonnull)SDKVersion SWIFT_WARN_UNUSED_RESULT;
- (void)setRemoteConfigSiteIdWith:(NSString * _Nonnull)siteId;
- (void)setSharedNamespaceWithUuid:(NSString * _Nonnull)namespace_;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("VisxTableViewCell")
@interface VisxTableViewCell : UITableViewCell
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull visxCellIdentifier;)
+ (NSString * _Nonnull)visxCellIdentifier SWIFT_WARN_UNUSED_RESULT;
- (void)showAdWithAdView:(VisxAdView * _Nonnull)adView tableView:(UITableView * _Nonnull)tableView;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
